
import "./globals.css";
import Navbar from "@/components/Navbar/page.jsx";
import { Providers } from "./providers";
import { ToastBar, Toaster } from "react-hot-toast";
export const metadata = {
  title: "AgriGuard",
  description: "Generated by Shailendra Sahani",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen overflow-x-hidden overflow-y-auto">
        <div className="flex flex-col min-h-screen">
        <Providers>
        <Navbar />
        <main className="flex-grow">
        {children}
        </main>
        </Providers>
        <Toaster position="top-right" />
        </div>
      </body>
    </html>
  );
}
